version: '3.8'

services:
  url-shortener-service:
    image: marcusju23/urlshortener:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8090"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/urlshortener
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
